### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by ulkaio** [ksmt88/grpc-web-chat#1]

**Comment by ulkaio** [comment]
Hi dude, thanks for uploading this, have you face any cors issue, have you did anything else other than `docker-compose up` to get it working. I am running docker through minikube and stuck on this 
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/chat.Chat/GetMessages. (Reason: CORS request did not succeed).`

**Comment by ksmt88** [comment]
@ulkaio 
There is no problem with cors.
cors settings are in envoy.yaml.

I will try it with kubernetes.

**Comment by ulkaio** [comment]
There were some issue on docker daemon running on minikube, it's working on docker docker desktop, closing this, thanks.
